import Head from "next/head";
import Features from "../components/pages/index/Features";
import Posters from "../components/pages/index/Posters";

export default function Index({ trending, tvseries, movies }) {
  return (
    <>
      <Head>
        <title>PyramidTV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-6 pt-14">
        <Posters />
        <Features title="Trending" data={trending} />
        <Features title="TV Series" data={tvseries} />
        <Features title="Movies" data={movies} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch APIS
  const trending = await fetch(
    `https://api.themoviedb.org/3/trending/all/day?api_key=284324d34929646388e9917f8c8608b0&page=1`
  ).then((response) => response.json());

  const tvseries = await fetch(
    `https://api.themoviedb.org/3/discover/tv?api_key=284324d34929646388e9917f8c8608b0&page=1&sort_by=popularity.desc`
  ).then((response) => response.json());

  const movies = await fetch(
    `https://api.themoviedb.org/3/discover/movie?api_key=284324d34929646388e9917f8c8608b0&page=1&sort_by=popularity.desc`
  ).then((response) => response.json());

  return {
    props: {
      trending: trending,
      tvseries: tvseries,
      movies: movies,
    },
  };
}
